config/routes.rb
Pstories::Application.routes.draw do
  root 'stories#index'

  resources :stories do
    resources :lines
    resources :characters
  end

end

app/models/character.rb
class Character < Sequel::Model
  one_to_many :lines
  many_to_many :stories

  def validate
    super
    validates_presence :name
  end
end

app/models/line.rb
class Line < Sequel::Model
  many_to_one :story
  many_to_one :character

  def validate
    super
    validates_presence [:line_item, :sequence, :story_id]
    validates_unique :sequence
  end

  def self.seq
    self.max(:sequence).to_f+1
  end
end

app/models/story.rb
# TODO[9] - DB mess, see "git log --format=%B -n 1 c3c3086"
# TODO[9] - couple examples: STORY[:id].add_character -> merrily saves duplicates
# TODO[9] - UPDATE: this is intentional. use story.title (or .id) as a namespace

class Story < Sequel::Model
  one_to_many :lines
  many_to_many :characters

  def validate
    super
    validates_presence [:title]
    validates_unique :title
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

  def index
    @story = Story[params[:story_id]]
    @line = Line.new
  end

  def edit
    @story = Story[params[:story_id]]
    @line = @story.lines_dataset.first(id: params[:id])
    @line_type = if @line.character_id
                   'Dialogue'
                 else
                   'Plot'
                 end
  end

  def update
    @story = Story[params[:story_id]]
    @line = @story.lines_dataset.first(id: params[:id])
    @line.character.update(params[:character].permit(:name))
    @line.update(params[:line].permit(:plot_item,:dialogue_item))
    redirect_to story_lines_url(@story)
  end

  def create
    @story = Story[params[:story_id]]
    # TODO[8] - not checking capitalization errors
    @character_id = unless params[:name].empty?
                   Character.find_or_create( name: params[:name]).id
                 else
                   nil
                 end
    # TODO[7] - once TODO[6] returns an object this whole mess can be made safe
    @line = Line.new(line_item: params[:line_item],
                     sequence: Line.seq,
                     character_id: @character_id)
    @story.add_line @line
    @story.add_character Character[@character_id] if @character_id
    redirect_to story_lines_url(@story)
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
    @story = Story.new
  end

  def create
    @story = Story.new( story_params )
    if @story.save
      redirect_to story_lines_url(@story.id)
    end
  end

  def destroy
    @story = Story[ params[:id] ]
    @story.lines_dataset.destroy
    @story.remove_all_characters
    @story.destroy
    redirect_to root_url
  end

  private

    def story_params
      params.require(:story).permit(:title)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title pstories
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    = yield

    footer = debug(params) if Rails.env.development?

app/views/lines/edit.html.slim
/ TODO[1] - find a better way then <table> in all the views
table
  tr
    / TODO[2] - needs to be DRYed (render the page only according to @line.character_id,
      TODO[2] -   without cluttering the view with code
    - if @line.character_id
      th Character
    th = @line_type
  = form_for @line, url: story_line_url(@story,@line), method: :patch  do |l|
    tr
      - if @line.character_id
        = fields_for @line.character do |char_fields|
          td = char_fields.text_field :name
      td = l.text_area :line_item
      td = l.submit 'hit it'
p = link_to 'Back', story_lines_path(@story.id)

app/views/lines/index.html.slim
/ TODO[2&3] - 3rd location where layout depends on line type (plot, dialogue)
/ TODO[2&3] - _plot partial?
table
  tr
    th Character
    th Plot or Dialogue item
  / TODO[6] - where to start...
  / TODO[6] -(a) reorganize form so that it actually returns a line object in params
  / TODO[6] -    (see params for stories#create)
  = form_for @line, url: story_lines_url(@story), method: :post do |l|
    tr
      td = text_field_tag :name
      td = text_area_tag :line_item
      td = l.submit 'go'
p Hint: character name not needed for plot item

div = link_to 'Back', root_path
h1 = @story.title

/ TODO[10] - concatenating char and line_item in model?
/ TODO[10] - some of the logic could removed
/ TODO[10] - def name; [first, last].join(' '); end in contact.rb
/ TODO[10] - (source: everyday rails testing with rails)
table
  - @story.lines.each do |l|
    tr
      td = link_to 'Edit', edit_story_line_path(@story.id,l.id)
      td> #{l.character_id ? l.character.name : ""}
      td> -
      td = l.line_item

app/views/stories/index.html.slim
h1 Here be stories

table
  th Title

  - @stories.each do |s|
    tr
      td = s.title
      td = link_to 'Show', story_lines_path(s.id)
      td = link_to 'Destroy', story_path(s.id),
                   method: :delete, data: { confirm: 'Sure about this hotshot?' }

h3 I dare you to make a new story
= form_for @story do |s|
  = s.label :title
  = s.text_field :title
  = s.submit 'shoot'

app/views/stories/show.html.slim
h1 = @story.title

table
  - @story.lines.each do |l|
    tr
      td> #{l.character.name}
      td> -
      td = l.plot_item ? l.plot_item : l.dialogue_item

= link_to 'Back', root_path